### ISSUE TITLE
Meson does not generate bin

### ISSUE THREAD

**Issue by robertsanseries** [project-hawk/hawk-desktop#1]
@TingPing Can you tell me why the bin is not generated?

**Comment by TingPing** [comment]
At a glance I don't see anything wrong, could you better explain your problem?

**Comment by robertsanseries** [comment]
@TingPing Does not generate binary in /usr/bin folder

### com.github.project-hawk.hawk

![captura de tela de 2017-07-12 18-23-06](https://user-images.githubusercontent.com/11967501/28140618-66cd3594-672f-11e7-8cc5-e8e79b3d1544.png)

![captura de tela de 2017-07-12 18-20-13](https://user-images.githubusercontent.com/11967501/28140492-e7b5136c-672e-11e7-8f3d-2132d8150e88.png)

**Comment by TingPing** [comment]
You need to make the input file executable: `chmod +x com.github.project-hawk.hawk.in` then reconfigure.

**Comment by robertsanseries** [comment]
@TingPing thank you brother! This made me come up with the following solution: 

```
configure_file = '@0@/com.github.project-hawk.hawk'.format(meson.current_build_dir())
install_data(configure_file, install_dir: 'bin', install_mode: 'rwxr-xr-x')
```

**Comment by TingPing** [comment]
> configure_file = '@0@/com.github.project-hawk.hawk'.format(meson.current_build_dir())

That is certainly wrong, just make the input file executable.

**Comment by robertsanseries** [comment]
I'll modify the permission then! Many thanks for the tips! :1st_place_medal:
